export const data = [
    {
        question: "Which of the following is the national flower of India?",
        options1: "Lotus",
        options2: "Rose",
        options3: "Sunflower",
        options4: "Marigold",
        ans: 1,
    },
    {
        question: "Who is known as the 'Father of the Nation' in India?",
        options1: "Jawaharlal Nehru",
        options2: "Mahatma Gandhi",
        options3: "Sardar Patel", 
        options4: "Bhagat Singh",
        ans: 2,
    },
    {
        question: "Where is the Taj Mahal located?",
        options1: "New Delhi",
        options2: "Mumbai",
        options3: "Agra",
        options4: "Jaipur",
        ans: 3,
    },
    {
        question: "Which festival is known as the 'Festival of Lights' in India?",
        options1: "Holi",
        options2: "Eid", 
        options3: "Diwali", 
        options4: "Christmas",
        ans: 3,
    },
    {
        question: "Kathakali is a traditional dance form of which Indian state?",
        options1: "Tamil Nadu",
        options2: "Kerala",
        options3: "Karnataka",
        options4: "Andhra Pradesh",
        ans: 2,
    },
    {
        question: "Which Indian monument is known as the 'Symbol of Love'?",
        options1: "India Gate",
        options2: "Gateway of India",
        options3: "Taj Mahal",
        options4: "Qutub Minar",
        ans: 3,
    },
    {
        question: "Which Indian city is known as the 'Pink City'?",
        options1: "Udaipur",
        options2: "Jodhpur",
        options3: "Jaipur",
        options4: "Bikaner",
        ans: 3,
    },
    {
        question: "What is the traditional folk dance of Gujarat?",
        options1: "Garba",
        options2: "Bhangra",
        options3: "Bharatanatyam",
        options4: "Odissi",
        ans: 1,
    },
    {
        question: "In which state is the Sun Temple of Konark located?",
        options1: "West Bengal",
        options2: "Odisha", 
        options3: "Madhya Pradesh",
        options4: "Bihar",
        ans: 2,
    },
    {
        question: "Which festival marks the beginning of the New Year in Tamil Nadu?",
        options1: "Onam",
        options2: "Baisakhi",
        options3: "Pongal",
        options4: "Ugadi",
        ans: 3,
    },
    {
        question: "Which is the oldest known language in India?",
        options1: "Hindi",
        options2: "Tamil",
        options3: "Sanskrit",
        options4: "Telugu",
        ans: 3,
    },
    {
        question: "Who was the first Indian woman to win a Nobel Prize?",
        options1: "Indira Gandhi",
        options2: "Mother Teresa",
        options3: "Sarojini Naidu",
        options4: "Kalpana Chawla",
        ans: 2,
    },
    {
        question: "Which of these festivals is a harvest festival in India?",
        options1: "Holi",
        options2: "Diwali",
        options3: "Lohri",
        options4: "Navratri",
        ans: 3,
    },
    {
        question: "Which Indian state is famous for the classical dance form Bharatanatyam?",
        options1: "Tamil Nadu",
        options2: "Kerala",
        options3: "Karnataka",
        options4: "Odisha",
        ans: 1,
    },
    {
        question: "The Ajanta and Ellora caves are located in which state?",
        options1: "Maharashtra",
        options2: "Rajasthan",
        options3: "Madhya Pradesh",
        options4: "Karnataka",
        ans: 1,
    },
    {
        question: "Which Indian festival is celebrated with a bonfire and marks the end of winter?",
        options1: "Lohri",
        options2: "Eid",
        options3: "Navratri",
        options4: "Raksha Bandhan",
        ans: 1,
    },
    {
        question: "In which state is the Ratha Yatra festival celebrated?",
        options1: "Odisha",
        options2: "Gujarat",
        options3: "West Bengal",
        options4: "Tamil Nadu",
        ans: 1,
    },
    {
        question: "What is the main ingredient of the Indian dish 'Sambar'?",
        options1: "Chickpea",
        options2: "Lentil",
        options3: "Rice",
        options4: "Wheat",
        ans: 2,
    },
    {
        question: "The Khajuraho temples are famous for their?",
        options1: "Carvings",
        options2: "Paintings",
        options3: "Sculptures",
        options4: "Architecture",
        ans: 3,
    },
    {
        question: "Which state is known for the 'Kumbh Mela' festival?",
        options1: "Uttar Pradesh",
        options2: "Madhya Pradesh",
        options3: "Rajasthan",
        options4: "Punjab",
        ans: 1,
    },
    {
        question: "Which Indian city is called the 'City of Lakes'?",
        options1: "Jaipur",
        options2: "Udaipur",
        options3: "Bhopal",
        options4: "Jaisalmer",
        ans: 2,
    },
    {
        question: "The traditional dance 'Ghoomar' belongs to which state?",
        options1: "Rajasthan",
        options2: "Madhya Pradesh",
        options3: "Gujarat",
        options4: "Punjab",
        ans: 1,
    },
    {
        question: "What is the main theme of the Indian festival 'Raksha Bandhan'?",
        options1: "Brotherhood",
        options2: "Victory of Good over Evil",
        options3: "Bond between brother and sister",
        options4: "New Year celebration",
        ans: 3,
    },
    {
        question: "Which Indian king built the Iron Pillar in Delhi?",
        options1: "Chandragupta II",
        options2: "Ashoka",
        options3: "Samudragupta",
        options4: "Harsha",
        ans: 1,
    },
    {
        question: "What is the famous folk dance of Punjab?",
        options1: "Bhangra",
        options2: "Garba",
        options3: "Bharatanatyam",
        options4: "Odissi",
        ans: 1,
    },
    {
        question: "Who wrote the Indian national anthem 'Jana Gana Mana'?",
        options1: "Mahatma Gandhi",
        options2: "Rabindranath Tagore",
        options3: "Jawaharlal Nehru",
        options4: "Sardar Patel",
        ans: 2,
    },
    {
        question: "Which state is famous for the 'Bihu' festival?",
        options1: "West Bengal",
        options2: "Assam",
        options3: "Bihar",
        options4: "Tripura",
        ans: 2,
    },
    {
        question: "The Red Fort in Delhi was built by which Mughal emperor?",
        options1: "Akbar",
        options2: "Babur",
        options3: "Shah Jahan",
        options4: "Aurangzeb",
        ans: 3,
    },
    {
        question: "Which Indian leader is known for his 'Salt March' against British rule?",
        options1: "Subhas Chandra Bose",
        options2: "Mahatma Gandhi",
        options3: "Jawaharlal Nehru",
        options4: "Bhagat Singh",
        ans: 2,
    },
    {
        question: "Which Indian festival involves kite flying, celebrated mainly in Gujarat?",
        options1: "Holi",
        options2: "Makar Sankranti",
        options3: "Diwali",
        options4: "Onam",
        ans: 2,
    },
    {
        question: "The classical dance form 'Kathak' originated from which region of India?",
        options1: "North India",
        options2: "South India",
        options3: "East India",
        options4: "West India",
        ans: 1,
    }
];