export const data = [
    {
        question: "Which of the following is the national flower of India?",
        options1: "Lotus",
        options2: "Rose",
        options3: "Sunflower",
        options4: "Marigold",
        ans: 1,
    },
    {
        question: "Who is known as the 'Father of the Nation' in India?",
        options1: "Jawaharlal Nehru",
        options2: "Mahatma Gandhi",
        options3: "Sardar Patel", 
        options4: "Bhagat Singh",
        ans: 2,
    },
    {
        question: "Where is the Taj Mahal located?",
        options1: "New Delhi",
        options2: "Mumbai",
        options3: "Agra",
        options4: "Jaipur",
        ans: 3,
    },
    {
        question: "Which festival is known as the 'Festival of Lights' in India?",
        options1: "Holi",
        options2: "Eid", 
        options3: "Diwali", 
        options4: "Christmas",
        ans: 3,
    },
    {
        question: "Kathakali is a traditional dance form of which Indian state?",
        options1: "Tamil Nadu",
        options2: "Kerala",
        options3: "Karnataka",
        options4: "Andhra Pradesh",
        ans: 2,
    },
    {
        question: "Which Indian monument is known as the 'Symbol of Love'?",
        options1: "India Gate",
        options2: "Gateway of India",
        options3: "Taj Mahal",
        options4: "Qutub Minar",
        ans: 3,
    },
    {
        question: "Which Indian city is known as the 'Pink City'?",
        options1: "Udaipur",
        options2: "Jodhpur",
        options3: "Jaipur",
        options4: "Bikaner",
        ans: 3,
    },
    {
        question: "What is the traditional folk dance of Gujarat?",
        options1: "Garba",
        options2: "Bhangra",
        options3: "Bharatanatyam",
        options4: "Odissi",
        ans: 1,
    },
    {
        question: "In which state is the Sun Temple of Konark located?",
        options1: "West Bengal",
        options2: "Odisha", 
        options3: "Madhya Pradesh",
        options4: "Bihar",
        ans: 2,
    },
    {
        question: "Which festival marks the beginning of the New Year in Tamil Nadu?",
        options1: "Onam",
        options2: "Baisakhi",
        options3: "Pongal",
        options4: "Ugadi" ,
        ans: 3,
    }
];
